version: '3.3'
services:
    web:
        ports:
            - '80:8000'
        volumes:
            - './app:/app'
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - FLASK_APP=main.py
            - FLASK_DEBUG=1
            - FLASK_KEY=CHANGETHISKEY
            - PYTHONUNBUFFERED=1
        command: flask run --host=0.0.0.0 --port=8000